name: tests-payments2

on: 
  pull_request:
    branches: [ main, dev ]

  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Perform Test
        env:
          STRIPE_KEY: ${{ secrets.STRIPE_KEY }}
      - run: cd payments && npm install && npm run test:ci
