name: tests-payments2

on:
  pull_request:
    branches: [dev]

  workflow_dispatch:

jobs:
  dev:
    runs-on: ubuntu-latest
    environment: dev

    steps:
      - uses: actions/checkout@v2
      - name: Perform Test
        run: cd orders && npm config set STRIPE_KEY=${STRIPE_KEY}
        npm install && npm run test:ci
        env:
          STRIPE_KEY: ${{ secrets.STRIPE_KEY }}
