name: tests-payments

on:
  pull_request:
    branches: [dev]

  workflow_dispatch:

jobs:
  dev:
    runs-on: ubuntu-latest
    environment: dev

    steps:
      - uses: actions/checkout@v2
      - name: Perform Test
        run: | #run milptiple commands
          cd orders && npm install &&
          npm config set STRIPE_KEY=${STRIPE_KEY} && npm run test:ci
        env:
          STRIPE_KEY: ${{ secrets.STRIPE_KEY }}
