name: tests-payments

on: pull_request
env:
  STRIPE_KEY: ${{ secrets.STRIPE_KEY }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Setup env
      - run: touch .env
          echo STRIPE_KEY=${{ secrets.STRIPE_KEY }} >> .env
          cat .env

      - name: Perform Test
      - uses: actions/checkout@v2
      - run: cd payments && npm install && npm run test:ci
      - env:
          STRIPE_KEY: ${{ secrets.STRIPE_KEY }}
